name: test-for-bug

on:
  # run on all pushes to any branch
  push:

jobs:
  test-bug:
    name: Test for bug
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install
      - name: Test with pytest
        run: poetry run pytest
